"""Reproduce the post-hoc SMS temporal probes; save predictions and generated claims.

Run from the repository root: python scripts/audit_sms_temporal.py
Uses the persisted linear baseline's specification, not a tuned temporal model.
The forward probe removes exact-text overlap with its training set and measures ham FPR only.
"""
import csv
import datetime as dt
import hashlib
import json
from pathlib import Path

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score
from sklearn.pipeline import make_pipeline

from train_sms_text_linear import ROOT, SRC, MSG


def main():
    raw = {r['message_id']: r['message'] for r in
           csv.DictReader(open(SRC, encoding='utf-8-sig', newline=''))}
    rows = list(csv.DictReader(open(MSG, encoding='utf-8', newline='')))
    texts = np.array([raw[r['message_id']] for r in rows])
    labels = np.array([int(r['label']) for r in rows])
    dates = [dt.datetime.strptime(r['date'], '%d/%m/%Y').date() if r['date'] else None
             for r in rows]
    train = np.array([r['split'] == 'train' for r in rows])
    early = np.array([d is not None and d < dt.date(2026, 8, 1) for d in dates])
    late = np.array([d is not None and d >= dt.date(2026, 8, 1) for d in dates])
    assert np.all(labels[late] == 0), 'Revisit the ham-only interpretation'
    overlap = late & np.isin(texts, texts[early])
    masks = {'registered_august': (train, ~train & late),
             'without_august': (train & early, ~train & early),
             'forward_august': (early, late & ~overlap)}
    out = {'status': 'post-hoc retrospective sensitivity; one fitted seed',
           'cutoff': '2026-08-01', 'undated_rows': sum(d is None for d in dates),
           'forward_excluded_exact_text_rows': int(overlap.sum()),
           'source_sha256': hashlib.sha256(Path(SRC).read_bytes()).hexdigest(),
           'split_sha256': hashlib.sha256(Path(MSG).read_bytes()).hexdigest(),
           'model': 'word TF-IDF (1,2), min_df=2, sublinear_tf; LR C=4, seed=0, max_iter=3000',
           'runs': {}}
    predictions = []
    for name, (tr, te) in masks.items():
        assert not np.any(tr & te)
        assert not set(texts[tr]) & set(texts[te]), name
        model = make_pipeline(TfidfVectorizer(ngram_range=(1, 2), min_df=2, sublinear_tf=True),
                              LogisticRegression(C=4, max_iter=3000, random_state=0))
        model.fit(texts[tr].tolist(), labels[tr])
        pred = (model.predict_proba(texts[te].tolist())[:, 1] > .5).astype(int)
        tn, fp, fn, tp = confusion_matrix(labels[te], pred, labels=[0, 1]).ravel()
        result = {'n_train': int(tr.sum()), 'n_test': int(te.sum()),
                  'tn': int(tn), 'fp': int(fp), 'fn': int(fn), 'tp': int(tp),
                  'fpr': float(fp / (tn + fp))}
        if np.any(labels[te] == 1):
            result.update(f1=float(f1_score(labels[te], pred)),
                          precision=float(precision_score(labels[te], pred)),
                          recall=float(recall_score(labels[te], pred)))
        out['runs'][name] = result
        for i, p in zip(np.flatnonzero(te), pred):
            predictions.append({'run': name, 'message_id': rows[i]['message_id'],
                                'label': int(labels[i]), 'prediction': int(p)})
    dest = Path(ROOT) / 'data/processed/sms'
    (dest / 'temporal_audit.json').write_text(json.dumps(out, indent=2) + '\n')
    with (dest / 'temporal_predictions.csv').open('w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=list(predictions[0]))
        writer.writeheader()
        writer.writerows(predictions)
    a, b, c = (out['runs'][n] for n in masks)
    macros = {'SmsTimeAugN': str(a['n_test']), 'SmsTimeAugFP': str(a['fp']),
              'SmsTimeAugFPR': f"{100*a['fpr']:.2f}", 'SmsTimeEarlyN': str(b['n_train']+b['n_test']),
              'SmsTimeEarlyTestN': str(b['n_test']), 'SmsTimeEarlyF': f"{b['f1']:.3f}",
              'SmsTimeForwardN': str(c['n_test']), 'SmsTimeForwardFPR': f"{100*c['fpr']:.2f}",
              'SmsTimeExcluded': str(int(overlap.sum())),
              'SmsTimeUndated': str(sum(d is None for d in dates))}
    tex = '% Generated by audit_sms_temporal.py; do not edit.\n'
    tex += ''.join('\\newcommand{\\'+k+'}{'+v+'}\n' for k, v in macros.items())
    (Path(ROOT) / 'papers/future_smishing/sections/gen_sms_temporal.tex').write_text(tex)
    print(json.dumps(out, indent=2))


if __name__ == '__main__':
    main()
