#!/usr/bin/env python3
"""
make_p1a_assets.py — Regenerate P1a's data-driven figures and tables FROM the dataset, so they
never drift from the numbers. Produces:

  papers/P1_dataset/figures/distribution.pdf   — scenario distribution (phishing), from data
  papers/P1_dataset/sections/tab_glance.tex    — "dataset at a glance" table
  papers/P1_dataset/sections/tab_baseline.tex  — URL baseline results (5 seeds + bootstrap CI)

The manuscript \input{}s the two .tex tables and \includegraphics the PDF, so a single run keeps
everything in sync. Hand-drawn conceptual diagrams (pipeline.pdf, examples.pdf) are intentionally
NOT regenerated here.

RUN:  python scripts/make_p1a_assets.py
"""
from __future__ import annotations
import math
import os
import sys

import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))
from train_url_baseline import (load, make_model, _metrics, bootstrap_ci,  # noqa: E402
                                COMPPHISH, DETERMINISTIC)

P1A = os.path.join(ROOT, "papers", "P1_dataset")
FIG = os.path.join(P1A, "figures")
SEC = os.path.join(P1A, "sections")
DATASET = os.path.join(ROOT, "data", "processed", "dataset_url.csv")
COMPPHISH_CSV = os.path.join(ROOT, "data", "processed", "vn_compphish.csv")

SCEN_ORDER = ["other", "bank", "ecommerce", "gov", "delivery", "social", "gaming", "telecom", "tax"]

METRICS = ("F1", "PR-AUC", "ROC-AUC", "FPR@R0.90")
# The reference-benchmark model suite (Section: canonical in-distribution benchmark). Display names
# are decoupled from the make_model() keys so the .tex reads naturally.
SUITE = [("LogReg", "Logistic Regression"), ("RandomForest", "Random Forest"),
         ("HistGB", "HistGB (grad.\\ boosting)"), ("MLP", "MLP")]


# ---------- figure ----------
def make_distribution(df):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    ph = df[df.label == "phishing"]
    counts = ph.scenario.value_counts().to_dict()
    order = [s for s in SCEN_ORDER if counts.get(s, 0)] + \
            [s for s in counts if s not in SCEN_ORDER]
    vals = [counts[s] for s in order]

    fig, ax = plt.subplots(figsize=(7.2, 3.2))
    ax.bar(range(len(order)), vals, color="0.82", edgecolor="black", width=0.72)
    ax.set_yscale("log")
    ax.set_ylabel("count (log scale)")
    ax.set_xticks(range(len(order)))
    ax.set_xticklabels(order, rotation=35, ha="right", fontsize=9)
    for i, v in enumerate(vals):
        ax.text(i, v * 1.08, str(v), ha="center", va="bottom", fontsize=8)
    ax.spines[["top", "right"]].set_visible(False)
    ax.set_ylim(top=max(vals) * 1.6)
    fig.tight_layout()
    out = os.path.join(FIG, "distribution.pdf")
    fig.savefig(out, bbox_inches="tight")
    plt.close(fig)
    print(f"[+] {out}")


# ---------- glance table ----------
def make_glance(df):
    s = df["collected_at"].astype(str).str.strip().str.slice(0, 10)
    dt = pd.to_datetime(s, format="%d/%m/%Y", errors="coerce").fillna(
        pd.to_datetime(s, format="%Y-%m-%d", errors="coerce"))
    def rng(mask):
        s = dt[mask].dropna()
        return f"{s.min():%Y-%m-%d} \\,--\\, {s.max():%Y-%m-%d}" if len(s) else "n/a"
    rows = []
    for tier, lab in [("gold", "gold (handled/verified)"), ("silver", "silver (under processing/feed)"),
                      ("bronze", "bronze (community/feed, $\\sim$50\\% dated)")]:
        if not (df.tier == tier).any():
            continue
        m = df.tier == tier
        rows.append((lab, int(((df.label == "phishing") & m).sum()),
                     int(((df.label == "benign") & m).sum()), rng(m & (df.label == "phishing"))))
    n_ph = int((df.label == "phishing").sum()); n_be = int((df.label == "benign").sum())
    sp = {s: int((df.split == s).sum()) for s in ("train", "val", "test")}
    src_be = df[df.label == "benign"].source.value_counts().to_dict()

    def f(n):  # thousands sep for LaTeX
        return f"{n:,}".replace(",", "{,}")

    body = "\n".join(
        f"{lab} & {f(p)} & {f(b)} & {d} \\\\" for lab, p, b, d in rows)
    esc = lambda s: s.replace("_", "\\_")
    src_str = ", ".join(esc(k) + " (" + f(v) + ")" for k, v in src_be.items())
    # P1a's preliminary content companion is a FIXED released sample. We do NOT auto-count the
    # data/raw/landing dirs any more: they are now shared with the P1b content-branch crawl and the
    # live-capture pipeline, so a glob would over-report P1a's companion subset. Keep it stable.
    n_pairs, n_pair_ph, n_pair_be = 868, 209, 659
    tex = f"""% AUTO-GENERATED by scripts/make_p1a_assets.py -- do not edit by hand.
\\begin{{table}}[t]
\\centering
\\small
\\caption{{Dataset at a glance, per label-confidence tier; dates are source-attested phishing
first-seen dates.}}
\\label{{tab:glance}}
\\begin{{tabular}}{{@{{}}l c c l@{{}}}}
\\toprule
Tier & \\#Phishing & \\#Benign & Date range (phishing first-seen) \\\\
\\midrule
{body}
\\midrule
\\textbf{{Total}} & \\textbf{{{f(n_ph)}}} & \\textbf{{{f(n_be)}}} & \\multicolumn{{1}}{{c}}{{{f(n_ph+n_be)} records}} \\\\
\\bottomrule
\\end{{tabular}}

\\smallskip
{{\\footnotesize Benign sources: {src_str}.
Splits: train {f(sp['train'])}, val {f(sp['val'])}, test {f(sp['test'])}.
Gated content companion: {f(n_pairs)} paired HTML$+$screenshot captures ({f(n_pair_ph)} phishing, {f(n_pair_be)} benign).}}
\\end{{table}}
"""
    out = os.path.join(SEC, "tab_glance.tex")
    open(out, "w", encoding="utf-8").write(tex)
    print(f"[+] {out}")


# ---------- baseline table ----------
def _train_eval(path, seeds=5, bootstrap=2000):
    from sklearn.model_selection import train_test_split
    df, feats = load(path)
    # primary benchmark = gold+silver only; the undated community 'bronze' stratum is released
    # as an expansion and reported separately
    if "tier" in df.columns:
        df = df[df["tier"].astype(str).isin(["gold", "silver"])].reset_index(drop=True)
    if "split" in df and df["split"].astype(str).isin(["train", "test"]).any():
        tr, te = df[df.split == "train"], df[df.split == "test"]
        if len(te) == 0 or te.y.nunique() < 2:
            tr, te = train_test_split(df, test_size=0.3, stratify=df.y, random_state=0)
    else:
        tr, te = train_test_split(df, test_size=0.3, stratify=df.y, random_state=0)
    yte = te.y.to_numpy()
    res = {"schema": "CompPhish" if feats is COMPPHISH else "Basic", "nfeat": len(feats)}
    # LogReg (deterministic)
    m = make_model("LogReg", 0).fit(tr[feats], tr.y)
    res["logreg"] = _metrics(yte, m.predict_proba(te[feats])[:, 1])
    # RandomForest over seeds
    runs = {k: [] for k in ("F1", "PR-AUC", "ROC-AUC", "FPR@R0.90")}
    last = None
    for s in range(seeds):
        m = make_model("RandomForest", s).fit(tr[feats], tr.y)
        sc = m.predict_proba(te[feats])[:, 1]; last = sc
        for k, v in _metrics(yte, sc).items():
            runs[k].append(v)
    res["rf_mean"] = {k: float(np.mean(v)) for k, v in runs.items()}
    res["rf_std"] = {k: float(np.std(v)) for k, v in runs.items()}
    res["ci"] = bootstrap_ci(yte, last, B=bootstrap)
    return res


def make_baseline():
    basic = _train_eval(DATASET)
    comp = _train_eval(COMPPHISH_CSV)

    def lr(r):  # logreg row
        m = r["logreg"]
        return (f"{m['F1']:.3f} & {m['PR-AUC']:.3f} & {m['ROC-AUC']:.3f} & {m['FPR@R0.90']:.3f}")

    def rf(r):
        me, sd = r["rf_mean"], r["rf_std"]
        return " & ".join(f"{me[k]:.3f}\\,$\\pm$\\,{sd[k]:.3f}"
                          for k in ("F1", "PR-AUC", "ROC-AUC", "FPR@R0.90"))

    def ci(r):
        c = r["ci"]
        return " & ".join(f"[{c[k][0]:.3f},\\,{c[k][1]:.3f}]"
                          for k in ("F1", "PR-AUC", "ROC-AUC", "FPR@R0.90"))

    tex = f"""% AUTO-GENERATED by scripts/make_p1a_assets.py -- do not edit by hand.
\\begin{{table}}[t]
\\centering
\\small
\\caption{{URL baseline results on PhishVN (temporal test split, \\texttt{{gold}}$+$\\texttt{{silver}}).
Random Forest is mean\\,$\\pm$\\,std over 5 seeds; brackets give the RF bootstrap 95\\% CI ($B=2000$).
Higher is better except FPR@90\\%rec.\\ (lower is better).}}
\\label{{tab:baseline}}
\\begin{{tabular}}{{@{{}}l l c c c c@{{}}}}
\\toprule
Feature schema & Model & F1 & PR-AUC & ROC-AUC & FPR@90\\%rec. \\\\
\\midrule
Basic ({basic['nfeat']} feat.)      & LogReg        & {lr(basic)} \\\\
                     & Random Forest & {rf(basic)} \\\\
                     & \\quad RF 95\\% CI & {ci(basic)} \\\\
\\midrule
CompPhish ({comp['nfeat']} feat.) & LogReg        & {lr(comp)} \\\\
                     & Random Forest & {rf(comp)} \\\\
                     & \\quad RF 95\\% CI & {ci(comp)} \\\\
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
    out = os.path.join(SEC, "tab_baseline.tex")
    open(out, "w", encoding="utf-8").write(tex)
    print(f"[+] {out}")


# ---------- reference benchmark (model suite on canonical split) ----------
def _load_bench():
    """CompPhish-schema features + labels + tier/split, plus the benign `source` stratum joined
    from the raw table (keyed on url_norm == the CompPhish `url`). Single-dataset only."""
    df, feats = load(COMPPHISH_CSV)
    raw = pd.read_csv(DATASET, low_memory=False)
    df["source"] = df["url"].map(raw.set_index("url_norm")["source"])
    return df, feats


def _f1_at(y, score, thr=0.5):
    """F1 at a fixed threshold, vectorised — the paired bootstrap calls this thousands of times,
    where the full _metrics() (which also fits ROC/PR curves) would be wasteful."""
    pred = score >= thr
    tp = float(np.sum(pred & (y == 1)))
    fp = float(np.sum(pred & (y == 0)))
    fn = float(np.sum(~pred & (y == 1)))
    return 2 * tp / (2 * tp + fp + fn) if (2 * tp + fp + fn) else 0.0


def paired_boot_f1(y, sa, sb, B=2000, seed=0):
    """95% CI for the F1 DIFFERENCE between two models, resampling the SAME test rows for both.

    Why this and not the two per-model CIs already in the table: overlapping marginal intervals do
    not mean two models are indistinguishable, and disjoint ones are not required for them to be
    distinguishable — the question is about the difference, which has its own (much narrower)
    distribution because both models are scored on identical rows and their errors are correlated.
    Comparing the marginal intervals by eye is the same mistake, in a different costume, as reading
    a ranking off two overlapping mean+/-std columns."""
    rng = np.random.default_rng(seed)
    n = len(y)
    d = []
    for _ in range(B):
        idx = rng.integers(0, n, n)
        yi = y[idx]
        if yi.min() == yi.max():                 # degenerate resample, no positives or no negatives
            continue
        d.append(_f1_at(yi, sa[idx]) - _f1_at(yi, sb[idx]))
    if not d:
        return 0.0, float("nan"), float("nan")
    d = np.asarray(d)
    return float(d.mean()), float(np.percentile(d, 2.5)), float(np.percentile(d, 97.5))


def _suite_eval(df, feats, seeds=5):
    """Canonical protocol: tier in {gold,silver}, train on split=='train', test on 'test'.
    Deterministic models reported once; stochastic models as mean/std over `seeds` seeds.
    Also returns each model's seed-0 test scores, so models can be compared on identical rows."""
    core = df[df.tier.astype(str).isin(["gold", "silver"])]
    tr, te = core[core.split == "train"], core[core.split == "test"]
    yte = te.y.to_numpy()
    out, scores = {}, {}
    for key, _disp in SUITE:
        srange = range(1) if key in DETERMINISTIC else range(seeds)
        runs = {k: [] for k in METRICS}
        for s in srange:
            m = make_model(key, s).fit(tr[feats], tr.y)
            sc = m.predict_proba(te[feats])[:, 1]
            if s == 0:
                scores[key] = sc
            for k, v in _metrics(yte, sc).items():
                runs[k].append(v)
        out[key] = {"mean": {k: float(np.mean(v)) for k, v in runs.items()},
                    "std": {k: float(np.std(v)) for k, v in runs.items()},
                    "det": key in DETERMINISTIC}
    return out, len(tr), len(te), scores, yte


def _basic_logreg():
    """LogReg on the 9-feature Basic schema, same canonical split — the schema ablation contrast."""
    df, feats = load(DATASET)
    core = df[df.tier.astype(str).isin(["gold", "silver"])]
    tr, te = core[core.split == "train"], core[core.split == "test"]
    m = make_model("LogReg", 0).fit(tr[feats], tr.y)
    return _metrics(te.y.to_numpy(), m.predict_proba(te[feats])[:, 1]), len(feats)


def make_benchmark(df, feats):
    """Reference in-distribution benchmark: the 4-model suite on the CompPhish canonical split.
    Returns the make_model key of the best model by mean PR-AUC (for the difficulty table)."""
    res, ntr, nte, scores, yte = _suite_eval(df, feats)
    basic, bfeat = _basic_logreg()
    best_f1 = max(r["mean"]["F1"] for r in res.values())
    best_key = max(res, key=lambda k: res[k]["mean"]["PR-AUC"])
    best_disp = dict(SUITE)[best_key]

    # Is the leading F1 actually ahead of the runner-up, or just nominally? Decided on the shared
    # test rows, not by comparing the two models' separate intervals.
    f1_rank = sorted(res, key=lambda k: -res[k]["mean"]["F1"])
    top_key, runner_key = f1_rank[0], f1_rank[1]
    f1_d, f1_lo, f1_hi = paired_boot_f1(yte, scores[top_key], scores[runner_key])
    f1_separated = not (f1_lo <= 0 <= f1_hi)
    # same question for the PR-AUC ranking that picks the model the difficulty table then uses
    pr_rank = sorted(res, key=lambda k: -res[k]["mean"]["PR-AUC"])
    pr_gap = res[pr_rank[0]]["mean"]["PR-AUC"] - res[pr_rank[1]]["mean"]["PR-AUC"]

    # Bootstrap 95% CI for the best model (by PR-AUC), so this single table carries the same
    # rigour the old two-model baseline table did (seed spread + test-set CI).
    core = df[df.tier.astype(str).isin(["gold", "silver"])]
    _tr, _te = core[core.split == "train"], core[core.split == "test"]
    _bm = make_model(best_key, 0).fit(_tr[feats], _tr.y)
    _ci = bootstrap_ci(_te.y.to_numpy(), _bm.predict_proba(_te[feats])[:, 1], B=2000)

    def cell(r, k):  # one metric cell: value (det) or mean +- std
        me, sd = r["mean"][k], r["std"][k]
        v = f"{me:.3f}" if r["det"] else f"{me:.3f}\\,$\\pm$\\,{sd:.3f}"
        # Bold the leading F1 ONLY if the paired bootstrap separates it from the runner-up. Bold is
        # a claim ("this model is best"), and on this test set the top two differ by less than the
        # bootstrap interval of their difference — so an unconditional bold asserts a ranking the
        # data does not support.
        if k == "F1" and abs(me - best_f1) < 1e-9 and f1_separated:
            v = "\\textbf{" + v + "}"
        return v

    rows = []
    for key, disp in SUITE:
        rows.append(f"{disp} & " + " & ".join(cell(res[key], k) for k in METRICS) + " \\\\")
        if key == best_key:  # CI sub-row sits directly under the model it belongs to
            rows.append("\\quad bootstrap 95\\% CI & "
                        + " & ".join(f"[{_ci[k][0]:.3f},\\,{_ci[k][1]:.3f}]" for k in METRICS)
                        + " \\\\")
    body = "\n".join(rows)
    top_disp, run_disp = dict(SUITE)[top_key], dict(SUITE)[runner_key]
    if f1_separated:
        bold_note = (f"\\textbf{{Bold}} marks the best F1 in the CompPhish suite: {top_disp} leads "
                     f"{run_disp} by ${f1_d:.3f}$ F1 on the shared test rows "
                     f"(paired bootstrap 95\\% CI $[{f1_lo:.3f},\\,{f1_hi:.3f}]$).")
    else:
        bold_note = (f"No F1 is marked best. Scoring the two leading models ({top_disp}, "
                     f"{run_disp}; seed-0 fits) on identical test rows puts them ${f1_d:.3f}$ apart "
                     f"with a paired bootstrap 95\\% CI of $[{f1_lo:.3f},\\,{f1_hi:.3f}]$, which "
                     f"spans zero --- the sign does not even survive the choice of seed, and this "
                     f"table therefore establishes no F1 ranking between them. Note that the "
                     f"per-model columns cannot answer this: overlapping marginal intervals neither "
                     f"imply nor deny a difference; only the interval of the \\emph{{difference}} "
                     f"does.")
    basic_row = ("Logistic Regression & "
                 + " & ".join(f"{basic[k]:.3f}" for k in METRICS) + " \\\\")
    fn = lambda n: f"{n:,}".replace(",", "{,}")  # LaTeX-safe thousands sep

    tex = f"""% AUTO-GENERATED by scripts/make_p1a_assets.py -- do not edit by hand.
\\begin{{table}}[t]
\\centering
\\small
\\caption{{PhishVN reference in-distribution benchmark: a model suite on the canonical CompPhish
temporal split (\\texttt{{gold}}$+$\\texttt{{silver}}, train $n={fn(ntr)}$, test $n={fn(nte)}$);
$\\pm$ is the standard deviation over seeds.}}
\\label{{tab:benchmark}}
\\begin{{tabular}}{{@{{}}l c c c c@{{}}}}
\\toprule
Model & F1 & PR-AUC & ROC-AUC & FPR@90\\%rec. \\\\
\\midrule
\\multicolumn{{5}}{{@{{}}l}}{{\\emph{{CompPhish schema ({len(feats)} feat.)}}}} \\\\
{body}
\\midrule
\\multicolumn{{5}}{{@{{}}l}}{{\\emph{{Basic schema ({bfeat} feat.): feature-schema ablation}}}} \\\\
{basic_row}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
    out = os.path.join(SEC, "tab_benchmark.tex")
    open(out, "w", encoding="utf-8").write(tex)
    # the significance verdict is a finding for the body text, but must stay derived (see the
    # matching note in make_p1b_assets.py) — so it ships as its own generated \input
    open(os.path.join(SEC, "gen_benchmark_verdict.tex"), "w", encoding="utf-8").write(
        "% AUTO-GENERATED by scripts/make_p1a_assets.py -- do not edit by hand.\n"
        + bold_note + "\n")
    print(f"[+] {out}")
    print(f"[+] {os.path.join(SEC, 'gen_benchmark_verdict.tex')}")
    print(f"    benchmark best-F1={best_f1:.3f}  best-PR-AUC model={best_key}")
    for key, disp in SUITE:
        r = res[key]
        print(f"    {disp:24s} " + "  ".join(f"{k}={r['mean'][k]:.3f}" for k in METRICS))
    print(f"    Basic LogReg ({bfeat}f)       " + "  ".join(f"{k}={basic[k]:.3f}" for k in METRICS))
    return best_key


def wilson(p, n, z=1.96):
    """Wilson score interval for a proportion. Not Wald: every cell in the difficulty table is a
    proportion over a stratum, and two of them are small (n=69) or near a boundary (FPR 0.018),
    exactly where Wald intervals run outside [0,1] and understate the width."""
    if not n:
        return (float("nan"), float("nan"))
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return (max(0.0, c - h), min(1.0, c + h))


def ci_str(p, n):
    lo, hi = wilson(p, n)
    return "---" if lo != lo else f"[{lo:.3f},\\,{hi:.3f}]"


# ---------- per-tier / per-stratum difficulty breakdown ----------
def make_difficulty(df, feats, best_key, seed=0):
    """Train the leaderboard's best model on the gold+silver CompPhish TRAIN split, then on TEST
    report phishing recall per label-confidence tier (gold/silver/bronze; bronze is unseen at
    train time) and benign FPR per negative stratum (registry, .vn-popular, global hard-negative).
    Fixed seed + threshold 0.5 for reproducibility."""
    core = df[df.tier.astype(str).isin(["gold", "silver"])]
    tr = core[core.split == "train"]
    m = make_model(best_key, seed).fit(tr[feats], tr.y)
    te = df[df.split == "test"].copy()
    te["pred"] = (m.predict_proba(te[feats])[:, 1] >= 0.5).astype(int)

    ph = te[te.y == 1]
    tiers = []  # (label, n, recall)  recall = TP/(TP+FN)
    for t in ("gold", "silver", "bronze"):
        sub = ph[ph.tier.astype(str) == t]
        tiers.append((t, len(sub), float(sub.pred.mean()) if len(sub) else float("nan")))

    be = te[te.y == 0]
    strata = []  # (label, desc, n, fpr)  fpr = FP/(FP+TN)
    for disp, desc, srcs in [
        ("registry", "certified trusted-org whitelist", ["tinnhiem_web", "tinnhiem_org"]),
        (".vn-popular", "Tranco \\texttt{.vn} top-list sample", ["tranco_vn"]),
        ("global hard-neg.", "Tranco global top-list sample", ["tranco"])]:
        sub = be[be.source.isin(srcs)]
        strata.append((disp, desc, len(sub), float(sub.pred.mean()) if len(sub) else float("nan")))

    disp_name = dict(SUITE)[best_key]

    def f(n):
        return f"{n:,}".replace(",", "{,}")

    tier_rows = "\n".join(
        f"\\texttt{{{t}}} & {'trained core' if t != 'bronze' else 'community expansion (unseen at train)'}"
        f" & {f(n)} & {r:.3f} & {ci_str(r, n)} \\\\" for t, n, r in tiers)
    strat_rows = "\n".join(
        f"{disp} & {desc} & {f(n)} & {v:.3f} & {ci_str(v, n)} \\\\"
        for disp, desc, n, v in strata)

    # Which tier comparisons actually survive their intervals? Stated rather than eyeballed: the
    # gold stratum is 69 rows, so its recall carries a +/-0.11 interval that a bare 0.681 hides.
    g, s, b = (dict((t, (n, r)) for t, n, r in tiers)[k] for k in ("gold", "silver", "bronze"))
    b_vs_core = wilson(b[1], b[0])[0] > max(wilson(g[1], g[0])[1], wilson(s[1], s[0])[1])
    core_sep = wilson(s[1], s[0])[0] > wilson(g[1], g[0])[1]
    bronze_claim = ("above both verified tiers with non-overlapping intervals" if b_vs_core
                    else "at a recall whose interval overlaps the verified tiers")
    gold_claim = ("and \\texttt{silver} separates from \\texttt{gold}" if core_sep else
                  "while \\texttt{gold} and \\texttt{silver} do not separate: at $n="
                  f"{g[0]}$ the \\texttt{{gold}} interval spans "
                  f"{wilson(g[1], g[0])[1] - wilson(g[1], g[0])[0]:.2f}")

    tex = f"""% AUTO-GENERATED by scripts/make_p1a_assets.py -- do not edit by hand.
\\begin{{table}}[t]
\\centering
\\small
\\caption{{Difficulty breakdown per stratum for the leaderboard's best model ({disp_name}, by mean
PR-AUC) on the temporal test split. Intervals are Wilson score 95\\% CIs.}}
\\label{{tab:difficulty}}
\\begin{{tabular}}{{@{{}}l l r c c@{{}}}}
\\toprule
Stratum & Description & $n$ & Value & 95\\% CI \\\\
\\midrule
\\multicolumn{{5}}{{@{{}}l}}{{\\emph{{Phishing detection recall by label-confidence tier
(recall $=$ TP/(TP$+$FN))}}}} \\\\
{tier_rows}
\\midrule
\\multicolumn{{5}}{{@{{}}l}}{{\\emph{{Benign false-positive rate by negative stratum
(FPR $=$ FP/(FP$+$TN))}}}} \\\\
{strat_rows}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
    out = os.path.join(SEC, "tab_difficulty.tex")
    open(out, "w", encoding="utf-8").write(tex)
    open(os.path.join(SEC, "gen_difficulty_verdict.tex"), "w", encoding="utf-8").write(
        "% AUTO-GENERATED by scripts/make_p1a_assets.py -- do not edit by hand.\n"
        f"The global hard-negative (Tranco) stratum drives almost all false positives, while the "
        f"curated \\texttt{{.vn}} negatives are near-trivial. Community-sourced \\texttt{{bronze}} "
        f"phishing --- never seen at training time --- is recovered {bronze_claim}, {gold_claim}.\n")
    print(f"[+] {out}")
    print(f"[+] {os.path.join(SEC, 'gen_difficulty_verdict.tex')}")
    print(f"    difficulty model={disp_name} (seed {seed})")
    for t, n, r in tiers:
        print(f"    phishing recall  {t:7s} n={n:5d}  recall={r:.3f}")
    for disp, _d, n, v in strata:
        print(f"    benign FPR       {disp:16s} n={n:5d}  FPR={v:.3f}")


def main():
    df = pd.read_csv(DATASET)
    os.makedirs(FIG, exist_ok=True)
    make_distribution(df)
    make_glance(df)
    # tab_baseline is superseded by the consolidated tab_benchmark (4-model suite + Basic ablation +
    # bootstrap CI); make_baseline() is kept for reference but no longer emitted into the paper.
    bench_df, bench_feats = _load_bench()
    best_key = make_benchmark(bench_df, bench_feats)
    make_difficulty(bench_df, bench_feats, best_key)
    print("Done. Recompile the P1a manuscript to pick up the regenerated assets.")


if __name__ == "__main__":
    main()
