#!/usr/bin/env python3
"""
make_p1a_assets.py — Regenerate P1a's data-driven figures and tables FROM the dataset, so they
never drift from the numbers. Produces:

  papers/P1a_dataset/figures/distribution.pdf   — scenario distribution (phishing), from data
  papers/P1a_dataset/sections/tab_glance.tex    — "dataset at a glance" table
  papers/P1a_dataset/sections/tab_baseline.tex  — URL baseline results (5 seeds + bootstrap CI)

The manuscript \input{}s the two .tex tables and \includegraphics the PDF, so a single run keeps
everything in sync. Hand-drawn conceptual diagrams (pipeline.pdf, examples.pdf) are intentionally
NOT regenerated here.

RUN:  python scripts/make_p1a_assets.py
"""
from __future__ import annotations
import os
import sys

import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))
from train_url_baseline import load, make_model, _metrics, bootstrap_ci, COMPPHISH  # noqa: E402

P1A = os.path.join(ROOT, "papers", "P1a_dataset")
FIG = os.path.join(P1A, "figures")
SEC = os.path.join(P1A, "sections")
DATASET = os.path.join(ROOT, "data", "processed", "dataset_url.csv")
COMPPHISH_CSV = os.path.join(ROOT, "data", "processed", "vn_compphish.csv")

SCEN_ORDER = ["other", "bank", "ecommerce", "gov", "delivery", "social", "gaming", "telecom", "tax"]


# ---------- figure ----------
def make_distribution(df):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    ph = df[df.label == "phishing"]
    counts = ph.scenario.value_counts().to_dict()
    order = [s for s in SCEN_ORDER if counts.get(s, 0)] + \
            [s for s in counts if s not in SCEN_ORDER]
    vals = [counts[s] for s in order]

    fig, ax = plt.subplots(figsize=(7.2, 3.2))
    ax.bar(range(len(order)), vals, color="0.82", edgecolor="black", width=0.72)
    ax.set_yscale("log")
    ax.set_ylabel("count (log scale)")
    ax.set_xticks(range(len(order)))
    ax.set_xticklabels(order, rotation=35, ha="right", fontsize=9)
    for i, v in enumerate(vals):
        ax.text(i, v * 1.08, str(v), ha="center", va="bottom", fontsize=8)
    ax.spines[["top", "right"]].set_visible(False)
    ax.set_ylim(top=max(vals) * 1.6)
    fig.tight_layout()
    out = os.path.join(FIG, "distribution.pdf")
    fig.savefig(out, bbox_inches="tight")
    plt.close(fig)
    print(f"[+] {out}")


# ---------- glance table ----------
def make_glance(df):
    dt = pd.to_datetime(df["collected_at"], errors="coerce", dayfirst=True)
    def rng(mask):
        s = dt[mask].dropna()
        return f"{s.min():%Y-%m-%d} \\,--\\, {s.max():%Y-%m-%d}" if len(s) else "n/a"
    rows = []
    for tier, lab in [("gold", "gold (handled/verified)"), ("silver", "silver (under processing)")]:
        m = df.tier == tier
        rows.append((lab, int(((df.label == "phishing") & m).sum()),
                     int(((df.label == "benign") & m).sum()), rng(m & (df.label == "phishing"))))
    n_ph = int((df.label == "phishing").sum()); n_be = int((df.label == "benign").sum())
    sp = {s: int((df.split == s).sum()) for s in ("train", "val", "test")}
    src_be = df[df.label == "benign"].source.value_counts().to_dict()

    def f(n):  # thousands sep for LaTeX
        return f"{n:,}".replace(",", "{,}")

    body = "\n".join(
        f"{lab} & {f(p)} & {f(b)} & {d} \\\\" for lab, p, b, d in rows)
    esc = lambda s: s.replace("_", "\\_")
    src_str = ", ".join(esc(k) + " (" + f(v) + ")" for k, v in src_be.items())
    tex = f"""% AUTO-GENERATED by scripts/make_p1a_assets.py — do not edit by hand.
\\begin{{table}}[t]
\\centering
\\small
\\caption{{Dataset at a glance, per label-confidence tier. Timestamps are phishing first-seen dates
from the NCSC feed; benign whitelist entries are largely undated (registry snapshot) and are placed
into splits by grouped random assignment.}}
\\begin{{tabular}}{{@{{}}l c c l@{{}}}}
\\toprule
Tier & \\#Phishing & \\#Benign & Date range (phishing first-seen) \\\\
\\midrule
{body}
\\midrule
\\textbf{{Total}} & \\textbf{{{f(n_ph)}}} & \\textbf{{{f(n_be)}}} & \\multicolumn{{1}}{{c}}{{{f(n_ph+n_be)} records}} \\\\
\\bottomrule
\\end{{tabular}}

\\smallskip
{{\\footnotesize Benign sources: {src_str}.
Splits: train {f(sp['train'])}, val {f(sp['val'])}, test {f(sp['test'])}.
Preliminary content subset: HTML $n\\approx112$, screenshot $n\\approx104$.}}
\\end{{table}}
"""
    out = os.path.join(SEC, "tab_glance.tex")
    open(out, "w", encoding="utf-8").write(tex)
    print(f"[+] {out}")


# ---------- baseline table ----------
def _train_eval(path, seeds=5, bootstrap=2000):
    from sklearn.model_selection import train_test_split
    df, feats = load(path)
    if "split" in df and df["split"].astype(str).isin(["train", "test"]).any():
        tr, te = df[df.split == "train"], df[df.split == "test"]
        if len(te) == 0 or te.y.nunique() < 2:
            tr, te = train_test_split(df, test_size=0.3, stratify=df.y, random_state=0)
    else:
        tr, te = train_test_split(df, test_size=0.3, stratify=df.y, random_state=0)
    yte = te.y.to_numpy()
    res = {"schema": "CompPhish" if feats is COMPPHISH else "Basic", "nfeat": len(feats)}
    # LogReg (deterministic)
    m = make_model("LogReg", 0).fit(tr[feats], tr.y)
    res["logreg"] = _metrics(yte, m.predict_proba(te[feats])[:, 1])
    # RandomForest over seeds
    runs = {k: [] for k in ("F1", "PR-AUC", "ROC-AUC", "FPR@R0.90")}
    last = None
    for s in range(seeds):
        m = make_model("RandomForest", s).fit(tr[feats], tr.y)
        sc = m.predict_proba(te[feats])[:, 1]; last = sc
        for k, v in _metrics(yte, sc).items():
            runs[k].append(v)
    res["rf_mean"] = {k: float(np.mean(v)) for k, v in runs.items()}
    res["rf_std"] = {k: float(np.std(v)) for k, v in runs.items()}
    res["ci"] = bootstrap_ci(yte, last, B=bootstrap)
    return res


def make_baseline():
    basic = _train_eval(DATASET)
    comp = _train_eval(COMPPHISH_CSV)

    def lr(r):  # logreg row
        m = r["logreg"]
        return (f"{m['F1']:.3f} & {m['PR-AUC']:.3f} & {m['ROC-AUC']:.3f} & {m['FPR@R0.90']:.3f}")

    def rf(r):
        me, sd = r["rf_mean"], r["rf_std"]
        return " & ".join(f"{me[k]:.3f}\\,$\\pm$\\,{sd[k]:.3f}"
                          for k in ("F1", "PR-AUC", "ROC-AUC", "FPR@R0.90"))

    def ci(r):
        c = r["ci"]
        return " & ".join(f"[{c[k][0]:.3f},\\,{c[k][1]:.3f}]"
                          for k in ("F1", "PR-AUC", "ROC-AUC", "FPR@R0.90"))

    tex = f"""% AUTO-GENERATED by scripts/make_p1a_assets.py — do not edit by hand.
\\begin{{table}}[t]
\\centering
\\small
\\caption{{URL baseline results on PhishVN (temporal test split, \\texttt{{gold}}$+$\\texttt{{silver}}).
Random Forest is mean\\,$\\pm$\\,std over 5 seeds; brackets give the RF bootstrap 95\\% CI ($B=2000$).
Higher is better except FPR@90\\%rec.\\ (lower is better).}}
\\label{{tab:baseline}}
\\begin{{tabular}}{{@{{}}l l c c c c@{{}}}}
\\toprule
Feature schema & Model & F1 & PR-AUC & ROC-AUC & FPR@90\\%rec. \\\\
\\midrule
Basic ({basic['nfeat']} feat.)      & LogReg        & {lr(basic)} \\\\
                     & Random Forest & {rf(basic)} \\\\
                     & \\quad RF 95\\% CI & {ci(basic)} \\\\
\\midrule
CompPhish ({comp['nfeat']} feat.) & LogReg        & {lr(comp)} \\\\
                     & Random Forest & {rf(comp)} \\\\
                     & \\quad RF 95\\% CI & {ci(comp)} \\\\
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
    out = os.path.join(SEC, "tab_baseline.tex")
    open(out, "w", encoding="utf-8").write(tex)
    print(f"[+] {out}")


def main():
    df = pd.read_csv(DATASET)
    os.makedirs(FIG, exist_ok=True)
    make_distribution(df)
    make_glance(df)
    make_baseline()
    print("Done. Recompile the P1a manuscript to pick up the regenerated assets.")


if __name__ == "__main__":
    main()
