#!/usr/bin/env python3
"""
p2_corpus_ext.py — the pre-committed extension of the P2 simulated corpus (2026-08-07).

A SEPARATE FILE because the pilot corpus in p2_generate_corpus.py is the artefact P3's published
evasion numbers were measured on: it stays byte-identical so those numbers remain reproducible, and
this module holds only what was added afterwards, auditable as its own object.

It exists because the paraphrase pilot resolved nothing — five contrasts in the time-stamped pre-specified
direction, none surviving the corrected test — and the extension was committed before any of it was
re-measured. Same guardrails as the corpus it extends: placeholder links only, generic sector
references, no real person targeted. Ships in the public code mirror as of
2026-09-05, on the reasoning recorded in p2_generate_corpus.py.

RUN:  python scripts/p2_corpus_ext.py
The pilot's post-mortem, the sizing argument and what was added: kept in the development repository, not shipped in this mirror
"""
from __future__ import annotations

LINK = "http://sim.example.vn/x"
L = LINK

# ---- SIMULATED phishing lures, +120 over the pilot's 73 ----
PHISH_EXT: dict[tuple[str, str], list[str]] = {
 ("sms", "bank"): [
  f"Tai khoan cua ban ghi nhan 3 lan nhap sai ma PIN. Mo khoa tai {L} truoc khi bi tam dung.",
  f"He thong phat hien the cua ban duoc dung tai nuoc ngoai. Xac nhan hoac tu choi tai {L}",
  f"Han muc chuyen tien cua ban da bi ha do canh bao rui ro. Khoi phuc tai {L}",
  f"Ban co khoan vay den han hom nay. Xem lich tra va xac nhan tai {L}",
  f"Dich vu ngan hang so cua ban se dung tu ngay mai neu chua cap nhat giay to. Lam tai {L}",
  f"Giao dich 4.900.000d dang cho duyet tu thiet bi moi. Duyet hoac chan tai {L}",
  f"Ban duoc mien phi chuyen khoan tron doi. Kich hoat goi tai {L} trong hom nay.",
  f"Thong tin nguoi thu huong cua ban chua khop. Cap nhat tai {L} de lenh chuyen khong bi tra.",
  f"Chung toi ghi nhan don khieu nai giao dich mang ten ban. Xac minh tai {L}",
  f"Sinh trac hoc cua tai khoan chua duoc cai dat. Bo sung tai {L} de giao dich tren 10 trieu.",
  f"Ma the cua ban lo tren mang theo canh bao he thong. Khoa va cap lai tai {L}",
  f"So du tiet kiem cua ban duoc cong lai suat thuong. Nhan tai {L} truoc 17h.",
  f"Tai khoan lau khong phat sinh giao dich se bi dong. Giu tai khoan bang cach xac nhan tai {L}",
  f"Ban vua duoc phe duyet han muc thau chi 20.000.000d. Kich hoat tai {L}",
  f"He thong can xac nhan lai so dien thoai nhan OTP cua ban. Cap nhat tai {L}",
  f"Phi duy tri the thang nay chua tru duoc do so du. Thanh toan tai {L} de tranh phat sinh lai.",
 ],
 ("sms", "gov"): [
  f"Giay phep lai xe cua ban sap het han. Gia han truc tuyen tai {L}",
  f"Ban co giay moi lam viec cua co quan chuc nang. Xem chi tiet tai {L}",
  f"Dot ra soat dan cu yeu cau xac nhan so dinh danh. Thuc hien tai {L} truoc 16h.",
  f"Ho so cap phieu ly lich tu phap cua ban can bo sung anh giay to. Nop tai {L}",
  f"Thong bao: ban chua dang ky tam tru theo quy dinh. Hoan tat tai {L}",
  f"Ket qua giai quyet khieu nai cua ban da co. Nhan ban dien tu tai {L}",
  f"Ban duoc chon khao sat dich vu cong va nhan ho tro. Tham gia tai {L}",
  f"Thong tin nguoi phu thuoc trong ho so cua ban chua khop. Dieu chinh tai {L}",
  f"Lich hen tiem chung cua ban da doi. Xac nhan lai tai {L}",
  f"Ho so dat dai mang ten ban dang cho bo sung. Nop giay to tai {L} truoc han.",
  f"Ban co thong bao hanh chinh moi tu co quan quan ly. Kiem tra tai {L}",
  f"So bao hiem y te dien tu cua ban chua kich hoat. Kich hoat tai {L} de dung khi kham.",
  f"Dang ky ho tro tien dien cho ho gia dinh dang mo. Nop ho so tai {L}",
 ],
 ("sms", "tax"): [
  f"Ban chua dang ky tai khoan thue dien tu ca nhan. Tao tai {L} de tranh bi phat cham.",
  f"He thong ghi nhan thu nhap tu hai noi tra. Ke khai bo sung tai {L}",
  f"Hoa don dien tu mang ma so thue cua ban co sai sot. Dieu chinh tai {L}",
  f"Ban duoc gia han nop thue theo chinh sach moi. Dang ky tai {L}",
  f"Thong bao: ho so hoan thue cua ban da duoc duyet. Nhan tien tai {L}",
  f"Ma so thue nguoi phu thuoc cua ban chua duoc cap. Dang ky tai {L}",
  f"Ban co khoan phat cham nop to khai. Xem va nop tai {L}",
  f"Chinh sach giam thue moi ap dung cho ban. Dang ky huong tai {L}",
  f"To khai cua ban bi tra ve do sai chi tieu. Sua tai {L} truoc 17h.",
  f"He thong yeu cau doi chieu chung tu khau tru cua ban. Tai len tai {L}",
 ],
 ("sms", "ecommerce"): [
  f"Ban co 1 don cho thanh toan sap huy. Giu don tai {L}",
  f"Ma giam gia cua ban chua duoc ap dung. Nhan lai tai {L}",
  f"San kiem tra thay tai khoan ban co giao dich bat thuong. Xac minh tai {L}",
  f"Ban duoc chon danh gia san pham nhan 200.000d. Tham gia tai {L}",
  f"Don hoan cua ban thieu anh san pham. Bo sung tai {L} de duoc duyet.",
  f"Vi cua ban co so du chua rut. Xac nhan tai khoan nhan tai {L}",
  f"Ban duoc nang hang thanh vien. Kich hoat quyen loi tai {L}",
  f"Don dat truoc cua ban den hang. Xac nhan thanh toan tai {L}",
  f"Phien dau gia cua ban sap ket thuc. Vao {L} de dat tiep.",
  f"Ban co qua sinh nhat tu san. Nhan tai {L} trong 48h.",
  f"Dia chi giao mac dinh cua ban khong hop le. Cap nhat tai {L}",
 ],
 ("sms", "delivery"): [
  f"Buu kien cua ban se hoan ve nguoi gui trong 24h. Giu hang tai {L}",
  f"Ban co 1 kien hang chua thanh toan COD. Xu ly tai {L}",
  f"Shipper ghi nhan dia chi khong tim thay. Chi duong lai tai {L}",
  f"Don cua ban bi huy do khong lien lac duoc. Kich hoat lai tai {L}",
  f"Kien hang cua ban can chu ky dien tu nguoi nhan. Ky tai {L}",
  f"Phi giao lai lan 2 la 20.000d. Thanh toan tai {L}",
  f"Buu pham cua ban dang cho tai buu cuc 3 ngay. Nhan lich giao tai {L}",
  f"Ma nhan hang cua ban da het han. Lay ma moi tai {L}",
  f"Don quoc te cua ban phat sinh thue nhap khau. Nop tai {L}",
  f"He thong can xac nhan ban van o dia chi cu. Tra loi tai {L}",
 ],
 ("sms", "social"): [
  f"Tai khoan cua ban bi han che do vi pham ban quyen. Khang nghi tai {L}",
  f"Ban co tin nhan cho tu mot trang chinh thuc. Xem tai {L}",
  f"Nhom cua ban sap bi go do bao cao hang loat. Phan hoi tai {L}",
  f"Ban duoc moi tham gia chuong trinh sang tao noi dung co thu nhap. Dang ky tai {L}",
  f"Anh cua ban duoc dung o mot trang khac. Kiem tra tai {L}",
  f"Mat khau cua ban xuat hien trong danh sach ro ri. Doi ngay tai {L}",
  f"Xac minh so dien thoai de mo lai binh luan tai {L}",
  f"Ban co 3 loi moi ket ban dang cho va 1 canh bao bao mat. Xem tai {L}",
 ],
 ("sms", "telecom"): [
  f"Goi cuoc cua ban het han hom nay. Gia han tai {L} de giu uu dai.",
  f"Ban co 1 hoa don cuoc chua xuat. Xem tai {L}",
  f"SIM cua ban duoc yeu cau cap lai tu thiet bi khac. Chan tai {L} neu khong phai ban.",
  f"Dang ky nhan ma so dep mien phi tai {L}",
  f"Thue bao cua ban duoc hoan 30.000d cuoc thua. Nhan tai {L}",
  f"Dich vu roaming cua ban chua bat. Kich hoat tai {L} truoc khi di.",
  f"Ban dang dung goi cu, doi sang goi re hon tai {L}",
  f"Thong tin chu the SIM chua trung khop giay to. Cap nhat tai {L}",
 ],
 ("email", "bank"): [
  f"Kinh gui Quy khach, he thong ghi nhan ba lan nhap sai ma xac thuc lien tiep tren tai khoan cua Quy khach. Vui long mo khoa tai {L} truoc khi dich vu bi tam dung.",
  f"Thong bao: the cua Quy khach vua duoc su dung tai mot diem chap nhan o nuoc ngoai. Neu khong phai Quy khach, vui long tu choi giao dich tai {L}.",
  f"Kinh gui Quy khach, han muc chuyen khoan cua Quy khach da duoc ha xuong theo canh bao rui ro. De khoi phuc han muc cu, vui long xac minh tai {L}.",
  f"Thong bao: khoan vay cua Quy khach den ky thanh toan trong hom nay. Vui long doi chieu lich tra no tai {L}.",
  f"Kinh gui Quy khach, ho so giay to dinh danh cua Quy khach da qua han cap nhat va dich vu ngan hang so co the bi tam ngung. Vui long bo sung tai {L}.",
  f"Thong bao: mot giao dich 4.900.000 VND dang cho phe duyet tu thiet bi chua dang ky. Vui long duyet hoac tu choi tai {L}.",
  f"Kinh gui Quy khach, Quy khach du dieu kien tham gia goi mien phi chuyen khoan tron doi. Vui long kich hoat tai {L} trong ngay hom nay.",
  f"Thong bao: thong tin sinh trac hoc cua tai khoan Quy khach chua duoc cai dat, cac giao dich gia tri lon se bi tu choi. Vui long hoan tat tai {L}.",
 ],
 ("email", "gov"): [
  f"Kinh gui Quy vi, giay phep do co quan cap cho Quy vi sap het thoi han hieu luc. Vui long lam thu tuc gia han truc tuyen tai {L}.",
  f"Thong bao: Quy vi co giay moi lam viec cua co quan chuc nang. Noi dung chi tiet duoc dang tai {L}.",
  f"Kinh gui Quy vi, dot ra soat du lieu dan cu yeu cau xac nhan lai so dinh danh ca nhan. Vui long thuc hien tai {L} truoc 16 gio.",
  f"Thong bao: ho so cap phieu ly lich tu phap cua Quy vi con thieu ban chup giay to tuy than. Vui long bo sung tai {L}.",
  f"Kinh gui Quy vi, ket qua giai quyet kien nghi cua Quy vi da duoc ban hanh. Ban dien tu duoc phat hanh tai {L}.",
  f"Thong bao: thong tin nguoi phu thuoc trong ho so cua Quy vi chua khop voi du lieu quan ly. Vui long dieu chinh tai {L}.",
  f"Kinh gui Quy vi, ho so dat dai mang ten Quy vi dang o trang thai cho bo sung. Vui long nop giay to tai {L} truoc thoi han.",
 ],
 ("email", "tax"): [
  f"Kinh gui Nguoi nop thue, he thong chua ghi nhan tai khoan thue dien tu ca nhan cua Quy vi. Vui long khoi tao tai {L} de tranh bi xu phat cham dang ky.",
  f"Thong bao: du lieu cho thay Quy vi co thu nhap tu hai noi chi tra trong ky. Vui long ke khai bo sung tai {L}.",
  f"Kinh gui Quy vi, hoa don dien tu mang ma so thue cua Quy vi co sai sot ve chi tieu. Vui long dieu chinh tai {L}.",
  f"Thong bao: Quy vi thuoc dien duoc gia han thoi han nop thue theo chinh sach moi. Vui long dang ky tai {L}.",
  f"Kinh gui Quy vi, ho so hoan thue cua Quy vi da duoc phe duyet. Vui long hoan tat thu tuc nhan tien tai {L}.",
  f"Thong bao: to khai cua Quy vi bi tra ve do sai chi tieu bat buoc. Vui long chinh sua tai {L} truoc 17 gio.",
  f"Kinh gui Quy vi, he thong yeu cau doi chieu chung tu khau tru thue cua Quy vi. Vui long tai len tai {L}.",
 ],
 ("email", "ecommerce"): [
  f"Kinh gui Quy khach, Quy khach dang co mot don cho thanh toan sap bi huy tu dong. Vui long giu don tai {L}.",
  f"Thong bao: ma giam gia cua Quy khach chua duoc ap dung vao don gan nhat. Vui long nhan lai tai {L}.",
  f"Kinh gui Quy khach, he thong ghi nhan giao dich bat thuong tren tai khoan mua sam cua Quy khach. Vui long xac minh tai {L}.",
  f"Thong bao: Quy khach duoc moi danh gia san pham va nhan phieu 200.000 VND. Vui long tham gia tai {L}.",
  f"Kinh gui Quy khach, yeu cau hoan hang cua Quy khach con thieu hinh anh san pham. Vui long bo sung tai {L} de duoc duyet.",
  f"Thong bao: vi cua Quy khach dang co so du chua rut. Vui long xac nhan tai khoan nhan tien tai {L}.",
  f"Kinh gui Quy khach, Quy khach vua duoc nang hang thanh vien. Vui long kich hoat quyen loi tai {L}.",
 ],
 ("email", "delivery"): [
  f"Kinh gui Quy khach, buu kien cua Quy khach se duoc hoan ve nguoi gui trong 24 gio toi. Vui long giu hang tai {L}.",
  f"Thong bao: Quy khach co mot kien hang chua thanh toan tien thu ho. Vui long xu ly tai {L}.",
  f"Kinh gui Quy khach, nhan vien giao hang ghi nhan khong tim thay dia chi. Vui long bo sung chi dan tai {L}.",
  f"Thong bao: kien hang cua Quy khach can chu ky dien tu cua nguoi nhan. Vui long ky tai {L}.",
  f"Kinh gui Quy khach, don quoc te cua Quy khach phat sinh khoan thue nhap khau. Vui long nop tai {L}.",
 ],
 ("email", "social"): [
  f"Kinh gui Quy khach, tai khoan cua Quy khach bi han che do khieu nai ban quyen noi dung. Vui long khang nghi tai {L}.",
  f"Thong bao: Quy khach co tin nhan cho tu mot trang da xac minh. Vui long xem tai {L}.",
  f"Kinh gui Quy khach, nhom do Quy khach quan tri co nguy co bi go sau nhieu bao cao. Vui long phan hoi tai {L}.",
  f"Thong bao: Quy khach duoc moi tham gia chuong trinh sang tao noi dung co chia se doanh thu. Vui long dang ky tai {L}.",
  f"Kinh gui Quy khach, mat khau cua Quy khach xuat hien trong mot danh sach du lieu ro ri. Vui long doi mat khau tai {L}.",
 ],
 ("email", "telecom"): [
  f"Kinh gui Quy khach, goi cuoc cua Quy khach het han trong hom nay. Vui long gia han tai {L} de giu uu dai hien tai.",
  f"Thong bao: Quy khach co mot hoa don cuoc chua duoc xuat. Vui long xem chi tiet tai {L}.",
  f"Kinh gui Quy khach, he thong nhan yeu cau cap lai SIM cho thue bao cua Quy khach tu mot thiet bi khac. Neu khong phai Quy khach, vui long chan tai {L}.",
  f"Thong bao: thue bao cua Quy khach duoc hoan 30.000 VND cuoc thua. Vui long nhan tai {L}.",
  f"Kinh gui Quy khach, thong tin chu the SIM cua Quy khach chua trung khop voi giay to. Vui long cap nhat tai {L}.",
 ],
}

# ---- BENIGN controls, +89, scaled to hold the pilot's phishing-to-benign ratio ----
BENIGN_EXT: dict[tuple[str, str], list[str]] = {
 ("sms", "bank"): [
  "Quy khach vua rut 500.000d tai ATM luc 08:15. So du kha dung: 2.310.000d.",
  "Thong bao: lai suat tiet kiem ky han 6 thang duoc dieu chinh tu ngay 01 thang sau.",
  "Quy khach da thanh toan hoa don dien thanh cong. Cam on Quy khach.",
  "Sao ke the tin dung ky nay cua Quy khach da duoc gui den dia chi thu dien tu dang ky.",
  "Chi nhanh gan nhat cua chung toi chuyen sang dia diem moi tu ngay 15. Xin cam on.",
  "Quy khach vua chuyen 1.200.000d thanh cong. So du kha dung: 3.880.000d.",
  "Nhac lich: ky han tiet kiem cua Quy khach dao han vao tuan sau.",
  "He thong se bao tri tu 23h den 1h sang mai. Mong Quy khach thong cam.",
  "Quy khach da dang ky thanh cong dich vu tra gop cho giao dich gan nhat.",
  "Cam on Quy khach da hoan tat cap nhat thong tin tai quay hom nay.",
 ],
 ("sms", "gov"): [
  "Ho so cua ban da chuyen sang buoc tham dinh. Thoi gian con lai du kien 3 ngay lam viec.",
  "Thong bao lich phun khu trung khu dan cu vao sang Chu Nhat tuan nay.",
  "Bo phan mot cua nghi lam viec ngay le, tiep nhan ho so tro lai vao thu Ba.",
  "Ket qua thu tuc cua ban da duoc gui qua duong buu dien.",
  "Nhac lich hop to dan pho vao 19h30 thu Sau tai nha van hoa.",
  "Lich cat nuoc bao tri khu vuc tu 8h den 12h ngay mai.",
  "Ban da nop le phi thanh cong. Bien lai duoc luu trong ho so dien tu.",
  "Thong bao: dot tiem chung mo rong dien ra tu ngay 10 den 20 thang nay tai tram y te.",
 ],
 ("sms", "tax"): [
  "To khai cua ban da duoc he thong tiep nhan thanh cong.",
  "Nhac han: thoi han quyet toan thue nam la ngay 31 thang 3.",
  "Chung tu khau tru thue cua ban da duoc phat hanh.",
  "He thong thue dien tu hoat dong binh thuong tro lai sau bao tri.",
  "Ho so dang ky nguoi phu thuoc cua ban da duoc chap nhan.",
  "Ban da hoan tat nghia vu thue ky nay. Cam on ban.",
  "Ban tin thue thang nay da duoc dang tren cong thong tin.",
 ],
 ("sms", "ecommerce"): [
  "Don hang cua ban da roi kho phan loai va dang tren duong giao.",
  "Cam on ban da danh gia san pham. 100 diem thuong da duoc cong.",
  "Yeu cau doi hang cua ban da duoc duyet. Vui long gui hang ve trong 7 ngay.",
  "Don hang #B21745 da duoc dong goi va cho don vi van chuyen lay.",
  "Diem thanh vien cua ban thang nay la 3.240 diem.",
  "Cua hang ban theo doi vua dang san pham moi.",
  "Don hang cua ban da duoc hoan tien ve phuong thuc thanh toan goc.",
  "Chuong trinh mien phi van chuyen ap dung cho don tu 150.000d trong thang nay.",
 ],
 ("sms", "delivery"): [
  "Buu kien cua ban da den buu cuc phat va se giao trong hom nay.",
  "Nhan vien giao hang se lien he ban trong khung gio 14h-17h.",
  "Kien hang cua ban da duoc giao cho nguoi nhan luc 10:22.",
  "Don cua ban dang tren duong den kho trung chuyen.",
  "Cam on ban da su dung dich vu. Ma van don da hoan tat.",
  "Buu cuc lam viec den 12h thu Bay, nghi Chu Nhat.",
  "Kien hang cua ban da duoc tiep nhan tai diem gui.",
 ],
 ("sms", "social"): [
  "Ban co 5 thong bao moi va 2 tin nhan chua doc.",
  "Ban be cua ban vua dang mot bai viet moi.",
  "Ky niem ngay nay nam truoc cua ban da san sang de xem lai.",
  "Trang ban theo doi vua phat truc tiep.",
  "Ban co 3 loi moi ket ban dang cho.",
  "Bai viet cua ban dat 120 luot thich trong hom nay.",
  "Nhom cua ban co 8 bai dang moi trong tuan.",
 ],
 ("sms", "telecom"): [
  "Goi cuoc cua ban con 12GB va 15 ngay su dung.",
  "Ban da nap thanh cong 100.000d vao tai khoan chinh.",
  "Cam on ban da gia han goi cuoc thang nay.",
  "Thue bao cua ban da hoan tat chuan hoa thong tin.",
  "Dich vu du lieu se bao tri tu 2h den 4h sang mai tai mot so khu vuc.",
  "Ban da huy thanh cong dich vu gia tri gia tang theo yeu cau.",
  "Hoa don cuoc thang nay cua ban la 180.000d, da thanh toan.",
 ],
 ("email", "bank"): [
  "Kinh gui Quy khach, sao ke tai khoan thang nay cua Quy khach da duoc phat hanh va luu trong ung dung ngan hang.",
  "Kinh gui Quy khach, chung toi xin thong bao lich nghi le cua he thong chi nhanh trong tuan toi.",
  "Kinh gui Quy khach, giao dich thanh toan hoa don cua Quy khach da duoc thuc hien thanh cong.",
  "Kinh gui Quy khach, chuong trinh uu dai lai suat tiet kiem se duoc dieu chinh tu dau thang sau.",
  "Kinh gui Quy khach, cam on Quy khach da hoan tat cap nhat thong tin dinh danh tai quay giao dich.",
  "Kinh gui Quy khach, he thong ngan hang truc tuyen se bao tri dinh ky trong dem nay tu 23 gio.",
  "Kinh gui Quy khach, ky han tiet kiem cua Quy khach se dao han vao tuan sau theo hop dong da ky.",
 ],
 ("email", "gov"): [
  "Kinh gui Quy vi, ho so cua Quy vi da chuyen sang buoc tham dinh, thoi gian xu ly con lai du kien ba ngay lam viec.",
  "Kinh gui Quy vi, ket qua thu tuc hanh chinh cua Quy vi da duoc gui qua duong buu dien theo dia chi dang ky.",
  "Kinh gui Quy vi, bo phan tiep nhan ho so nghi lam viec trong ngay le va tiep nhan tro lai vao thu Ba.",
  "Kinh gui Quy vi, le phi ho so cua Quy vi da duoc ghi nhan; bien lai dien tu duoc luu trong ho so.",
  "Kinh gui Quy vi, dot tiem chung mo rong se dien ra tu ngay 10 den ngay 20 thang nay tai tram y te phuong.",
 ],
 ("email", "tax"): [
  "Kinh gui Quy vi, to khai thue cua Quy vi da duoc he thong tiep nhan thanh cong.",
  "Kinh gui Quy vi, chung tu khau tru thue cua Quy vi da duoc phat hanh va luu tren he thong.",
  "Kinh gui Quy vi, ban tin chinh sach thue thang nay da duoc dang tai tren cong thong tin.",
  "Kinh gui Quy vi, ho so dang ky nguoi phu thuoc cua Quy vi da duoc chap nhan.",
  "Kinh gui Quy vi, he thong thue dien tu da hoat dong binh thuong tro lai sau ky bao tri.",
 ],
 ("email", "ecommerce"): [
  "Kinh gui Quy khach, don hang cua Quy khach da duoc dong goi va ban giao cho don vi van chuyen.",
  "Kinh gui Quy khach, yeu cau doi hang cua Quy khach da duoc phe duyet.",
  "Kinh gui Quy khach, cam on Quy khach da danh gia san pham; diem thuong da duoc cong vao tai khoan.",
  "Kinh gui Quy khach, khoan hoan tien cho don hang da huy da duoc chuyen ve phuong thuc thanh toan goc.",
  "Kinh gui Quy khach, ban tin san pham moi thang nay cua chung toi da duoc phat hanh.",
 ],
 ("email", "delivery"): [
  "Kinh gui Quy khach, buu kien cua Quy khach da den buu cuc phat va du kien duoc giao trong hom nay.",
  "Kinh gui Quy khach, kien hang cua Quy khach da duoc giao thanh cong cho nguoi nhan.",
  "Kinh gui Quy khach, don hang cua Quy khach dang tren duong den kho trung chuyen.",
  "Kinh gui Quy khach, cam on Quy khach da su dung dich vu chuyen phat cua chung toi.",
  "Kinh gui Quy khach, buu cuc thong bao lich lam viec trong dip le sap toi.",
 ],
 ("email", "social"): [
  "Kinh gui Quy khach, ban tom tat hoat dong tuan nay tren tai khoan cua Quy khach da san sang.",
  "Kinh gui Quy khach, chung toi da cap nhat dieu khoan su dung dich vu tu thang sau.",
  "Kinh gui Quy khach, tinh nang quan ly quyen rieng tu moi da duoc bo sung trong phan cai dat.",
  "Kinh gui Quy khach, cam on Quy khach da hoan tat thiet lap bao mat hai lop cho tai khoan.",
 ],
 ("email", "telecom"): [
  "Kinh gui Quy khach, hoa don cuoc thang nay cua Quy khach da duoc phat hanh va thanh toan thanh cong.",
  "Kinh gui Quy khach, goi cuoc du lieu cua Quy khach con 12GB va 15 ngay su dung.",
  "Kinh gui Quy khach, he thong du lieu se bao tri dinh ky trong dem tai mot so khu vuc.",
  "Kinh gui Quy khach, cam on Quy khach da hoan tat chuan hoa thong tin thue bao.",
 ],
}
